// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMD3i08EjBCXZzP7sT47oqH_sAooagfX0',
    appId: '1:477683893012:web:238e4fb7871751bce8f801',
    messagingSenderId: '477683893012',
    projectId: 'fluttertest-59fab',
    authDomain: 'fluttertest-59fab.firebaseapp.com',
    storageBucket: 'fluttertest-59fab.appspot.com',
    measurementId: 'G-NVFENJJL63',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8vgXPpWyJ5KmDJ8_tzMSd3z9nMkSi_Ls',
    appId: '1:477683893012:android:c40db6d196090ab9e8f801',
    messagingSenderId: '477683893012',
    projectId: 'fluttertest-59fab',
    storageBucket: 'fluttertest-59fab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBS2R_qw0wqHGYOWZU8r-IDZ-HWd5jv2i4',
    appId: '1:477683893012:ios:9cce4bfd85e3fa51e8f801',
    messagingSenderId: '477683893012',
    projectId: 'fluttertest-59fab',
    storageBucket: 'fluttertest-59fab.appspot.com',
    androidClientId: '477683893012-bo7at16qqhqpasi6a34atiueprscmer1.apps.googleusercontent.com',
    iosClientId: '477683893012-avjtqce0bjbc955gtcdfjap1l7373ol8.apps.googleusercontent.com',
    iosBundleId: 'com.tr.portfolio.trPortfolio',
  );
}
